In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

ds = pd.read_csv('MLR_mix.csv')
ds.head()

S&P department (spend)  Admin department(spend)  \
0                  101184                    70674   
1                   70132                    52030   
2                  149539                    98535   
3                   75821                    53649   
4                   97730                    68667   

   Operation department(spend) state  Profit  
0                        97009     A  259480  
1                        63587     B  137019  
2                       199994     A  495552  
3                        66500     B  165057  
4                        91754     B  247841

In [2]:
ds.tail()

S&P department (spend)  Admin department(spend)  \
45                   63540                    50907   
46                  114384                    83388   
47                   53199                    50191   
48                  131777                    89570   
49                  110643                    74362   

    Operation department(spend) state  Profit  
45                        57776     B  115258  
46                       126691     A  389887  
47                        52911     B  110874  
48                       160129     A  425351  
49                       112527     A  324743

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   S&P department (spend)       50 non-null     int64 
 1   Admin department(spend)      50 non-null     int64 
 2   Operation department(spend)  50 non-null     int64 
 3   state                        50 non-null     object
 4   Profit                       50 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 2.1+ KB


In [4]:
corr = ds.corr()
print(corr)

                             S&P department (spend)  Admin department(spend)  \
S&P department (spend)                     1.000000                 0.984560   
Admin department(spend)                    0.984560                 1.000000   
Operation department(spend)                0.976437                 0.980723   
Profit                                     0.982576                 0.993823   

                             Operation department(spend)    Profit  
S&P department (spend)                          0.976437  0.982576  
Admin department(spend)                         0.980723  0.993823  
Operation department(spend)                     1.000000  0.975566  
Profit                                          0.975566  1.000000  


In [5]:
x = ds.iloc[:, [0, 1, 2, 3]].values
y = ds.iloc[:, 4].values
print(x)
print(y)

[[101184 70674 97009 'A']
 [70132 52030 63587 'B']
 [149539 98535 199994 'A']
 [75821 53649 66500 'B']
 [97730 68667 91754 'B']
 [84544 60923 81618 'B']
 [117490 85379 146277 'A']
 [119913 86499 150579 'B']
 [145244 95108 189066 'B']
 [147217 95598 190309 'A']
 [81746 56815 72351 'B']
 [107967 74058 106215 'A']
 [74692 52493 64267 'A']
 [72228 52210 63719 'A']
 [96292 68521 90007 'B']
 [124506 86995 153382 'A']
 [113543 82796 122345 'B']
 [142585 94589 184603 'A']
 [118057 86227 146948 'A']
 [86260 63082 85320 'A']
 [63601 51026 59932 'A']
 [113200 76388 115984 'A']
 [141331 93725 171453 'B']
 [79667 54864 69102 'A']
 [112208 75407 115316 'B']
 [82622 59754 72987 'A']
 [127721 88888 153477 'B']
 [117901 85532 146822 'B']
 [147364 96275 191812 'B']
 [110661 75404 114864 'A']
 [107360 73604 100773 'B']
 [87194 63403 87468 'B']
 [75381 52575 66116 'A']
 [113427 78653 119763 'A']
 [103004 71720 100065 'B']
 [109249 74209 109578 'B']
 [134157 92647 167690 'B']
 [116481 83866 141719 'A']
 [8

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 3] = le.fit_transform(x[:, 3])
x

array([[101184, 70674, 97009, 0],
       [70132, 52030, 63587, 1],
       [149539, 98535, 199994, 0],
       [75821, 53649, 66500, 1],
       [97730, 68667, 91754, 1],
       [84544, 60923, 81618, 1],
       [117490, 85379, 146277, 0],
       [119913, 86499, 150579, 1],
       [145244, 95108, 189066, 1],
       [147217, 95598, 190309, 0],
       [81746, 56815, 72351, 1],
       [107967, 74058, 106215, 0],
       [74692, 52493, 64267, 0],
       [72228, 52210, 63719, 0],
       [96292, 68521, 90007, 1],
       [124506, 86995, 153382, 0],
       [113543, 82796, 122345, 1],
       [142585, 94589, 184603, 0],
       [118057, 86227, 146948, 0],
       [86260, 63082, 85320, 0],
       [63601, 51026, 59932, 0],
       [113200, 76388, 115984, 0],
       [141331, 93725, 171453, 1],
       [79667, 54864, 69102, 0],
       [112208, 75407, 115316, 1],
       [82622, 59754, 72987, 0],
       [127721, 88888, 153477, 1],
       [117901, 85532, 146822, 1],
       [147364, 96275, 191812, 1],
       [11

In [7]:
le.inverse_transform([0, 1])

array(['A', 'B'], dtype=object)

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('State', OneHotEncoder(), [3])], remainder = 'passthrough')
x = ct.fit_transform(x)
x

array([[1.0, 0.0, 101184, 70674, 97009],
       [0.0, 1.0, 70132, 52030, 63587],
       [1.0, 0.0, 149539, 98535, 199994],
       [0.0, 1.0, 75821, 53649, 66500],
       [0.0, 1.0, 97730, 68667, 91754],
       [0.0, 1.0, 84544, 60923, 81618],
       [1.0, 0.0, 117490, 85379, 146277],
       [0.0, 1.0, 119913, 86499, 150579],
       [0.0, 1.0, 145244, 95108, 189066],
       [1.0, 0.0, 147217, 95598, 190309],
       [0.0, 1.0, 81746, 56815, 72351],
       [1.0, 0.0, 107967, 74058, 106215],
       [1.0, 0.0, 74692, 52493, 64267],
       [1.0, 0.0, 72228, 52210, 63719],
       [0.0, 1.0, 96292, 68521, 90007],
       [1.0, 0.0, 124506, 86995, 153382],
       [0.0, 1.0, 113543, 82796, 122345],
       [1.0, 0.0, 142585, 94589, 184603],
       [1.0, 0.0, 118057, 86227, 146948],
       [1.0, 0.0, 86260, 63082, 85320],
       [1.0, 0.0, 63601, 51026, 59932],
       [1.0, 0.0, 113200, 76388, 115984],
       [0.0, 1.0, 141331, 93725, 171453],
       [1.0, 0.0, 79667, 54864, 69102],
       [0.0, 1.

In [9]:
x = x[:, 1:] #keep B
#x = x[:, [0, 2, 3, 4]] #keep A
x

array([[0.0, 101184, 70674, 97009],
       [1.0, 70132, 52030, 63587],
       [0.0, 149539, 98535, 199994],
       [1.0, 75821, 53649, 66500],
       [1.0, 97730, 68667, 91754],
       [1.0, 84544, 60923, 81618],
       [0.0, 117490, 85379, 146277],
       [1.0, 119913, 86499, 150579],
       [1.0, 145244, 95108, 189066],
       [0.0, 147217, 95598, 190309],
       [1.0, 81746, 56815, 72351],
       [0.0, 107967, 74058, 106215],
       [0.0, 74692, 52493, 64267],
       [0.0, 72228, 52210, 63719],
       [1.0, 96292, 68521, 90007],
       [0.0, 124506, 86995, 153382],
       [1.0, 113543, 82796, 122345],
       [0.0, 142585, 94589, 184603],
       [0.0, 118057, 86227, 146948],
       [0.0, 86260, 63082, 85320],
       [0.0, 63601, 51026, 59932],
       [0.0, 113200, 76388, 115984],
       [1.0, 141331, 93725, 171453],
       [0.0, 79667, 54864, 69102],
       [1.0, 112208, 75407, 115316],
       [0.0, 82622, 59754, 72987],
       [1.0, 127721, 88888, 153477],
       [1.0, 117901, 85532

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)
print('x_train:', x_train)
print('x_test:', x_test)
print('y_train:', y_train)
print('y_test:', y_test)

x_train: [[0.0 113427 78653 119763]
 [1.0 109249 74209 109578]
 [1.0 127721 88888 153477]
 [1.0 103004 71720 100065]
 [0.0 118057 86227 146948]
 [1.0 119913 86499 150579]
 [1.0 96292 68521 90007]
 [1.0 63540 50907 57776]
 [0.0 131777 89570 160129]
 [0.0 110661 75404 114864]
 [0.0 124506 86995 153382]
 [1.0 107360 73604 100773]
 [0.0 75381 52575 66116]
 [1.0 113543 82796 122345]
 [0.0 103666 72280 100346]
 [0.0 63601 51026 59932]
 [1.0 134089 91457 166994]
 [1.0 145244 95108 189066]
 [0.0 72228 52210 63719]
 [0.0 82622 59754 72987]
 [1.0 84544 60923 81618]
 [0.0 142585 94589 184603]
 [0.0 81818 57716 72492]
 [0.0 110643 74362 112527]
 [1.0 70132 52030 63587]
 [0.0 74692 52493 64267]
 [0.0 116481 83866 141719]
 [1.0 112208 75407 115316]
 [0.0 117490 85379 146277]
 [0.0 79667 54864 69102]
 [1.0 134157 92647 167690]
 [0.0 113200 76388 115984]
 [0.0 86260 63082 85320]
 [0.0 147217 95598 190309]
 [1.0 131088 89489 154742]
 [0.0 114384 83388 126691]
 [1.0 75821 53649 66500]
 [0.0 101184 70674

In [11]:
# y = mx + c
# y = Bx + a
# m = B = gradient = coefficient
# c = a = y-intercept = constant

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)
print('Coefficients, beta:', regressor.coef_)
print('Constant, alpha:', regressor.predict([[0, 0, 0, 0]]))

Coefficients, beta: [-7.64437381e+03  6.21135973e-01  6.94950794e+00 -1.91570893e-01]
Constant, alpha: [-247075.19282106]


In [12]:
# equal to 1 is good
# equal to 0 is not good

x = regressor.score(x_train, y_train)
print(x)

0.9889036771430355


In [13]:
y_pred = regressor.predict(x_test)
print(y_pred)
print(y_test)

[469131.79514153 314305.95098855 177031.76224272 251333.22466428
 492265.59457446 384791.47672058 212333.02403266 223303.09210661
 451563.42840049 265608.51763769]
[466013 305250 188824 241206 495552 397289 222793 229567 438294 247841]


In [14]:
from sklearn.metrics import r2_score
y = r2_score(y_pred, y_test)
print(y)

0.9906753471192893


In [15]:
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error(y_test, y_pred)
print(MSE)

114075328.33230376


In [18]:
# Estimate the profit gained if:
# S&P department spend=90020,
# Admin department spend = 55200,
# Operation department spend = 94230
# State = B

y_pred = regressor.predict([[1, 90020, 55200, 94230]])
print(y_pred)

[166756.20638859]
